"""empty message

Revision ID: 21edecf470ee
Revises: ffb7b395444c
Create Date: 2019-10-07 21:41:10.618094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21edecf470ee'
down_revision = 'ffb7b395444c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_stream', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'data_stream', 'user_account', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_stream', type_='foreignkey')
    op.drop_column('data_stream', 'user_id')
    # ### end Alembic commands ###
