"""empty message

Revision ID: 943fd295d8ad
Revises: 21edecf470ee
Create Date: 2019-10-08 12:24:22.118739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943fd295d8ad'
down_revision = '21edecf470ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_stream', sa.Column('timestamp', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_stream', 'timestamp')
    # ### end Alembic commands ###
