"""empty message

Revision ID: cb3efc15544c
Revises: 10befae7e163
Create Date: 2019-10-07 20:05:40.344718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3efc15544c'
down_revision = '10befae7e163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'data_stream', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_stream', type_='unique')
    # ### end Alembic commands ###
